couple bug fixes
ipdk-io/ipdk pull request #176
Opened 2022-06-28 00:31 UTC by qzhan16

fix couple bug in scripts

2022-06-28 13:26 UTC, mestery requested changes

2022-06-28 13:26 UTC, mestery commented on build/networking/scripts/build_p4sde.sh
> +cd "$SDE/p4-driver"
Please use this syntax instead:

```
pushd "$SDE/p4-driver"
git checkout 780b3dfa205815e87f4580383cc37bfa30187f7c
popd
```

2022-06-28 13:26 UTC, mestery commented on build/networking/scripts/build_p4sde.sh
> +cd "$SDE/p4-driver/tools/setup"
Instead of `cd`, use `pushd` and `popd`.

2022-06-28 23:19 UTC, qzhan16 commented on build/networking/scripts/build_p4sde.sh
> +cd "$SDE/p4-driver"
updated in new version, thanks

2022-06-29 19:43 UTC, mestery approved these changes

2022-07-07 08:19 UTC, a37a32 commented
Hi @mestery , any timeline when this PR will be merged? Thanks.

2022-07-07 12:54 UTC, mestery commented
Hi @qzhan16, can you rebase this change and then force push here so it re-triggers the CI jobs? Thanks!

2022-07-08 17:35 UTC, ipdksw commented
https://cbjenkins-fm.devtools.intel.com/teams-nex-epgsw-ipdkci/job/nex-epgsw-ipdkci/job/GitHub_MultiBranch_Pipelines/job/ipdk/job/PR-176/ Result:ABORTED JenkinsConsole:https://s3.ipdk.io/nex-epgsw-ipdkci/GitHub_MultiBranch_Pipelines/ipdk/PR-176-6/index.html GitCommit:https://github.com/ipdk-io/ipdk/commits/9a7896fcb9fedb76227c31888224df1bf51db8ba

2022-07-09 01:06 UTC, mestery approved these changes
Thanks for the fixes!

2022-07-09 01:06 UTC, merged