Rename proxy-container to ipu-storage-container
ipdk-io/ipdk pull request #182
Opened 2022-06-29 09:08 UTC by artek-koltun

Original proxy-container name was inherited from SPDK docker example.
However, to better convey the idea that it is placed on IPU side, it is better to rename container to highlight that fact.

2022-06-30 09:14 UTC, intelfisz approved these changes

2022-06-30 09:34 UTC, artek-koltun commented
> Original proxy-container name was inherited from SPDK docker example. However, to better convey the idea that this container is placed on IPU side, it is renamed to ipu-storage-container now.

Done

2022-06-30 13:28 UTC, mestery commented
When are you all going to work on #158 and #173? We have no GitHub Actions CI for this, and we need it, otherwise we can't verify this works. Further, we need this integrated with the `ipdk` CLI or it doesn't seem like it fits into the broader IPDK repository here.

2022-07-01 10:16 UTC, intelfisz commented
> When are you all going to work on #158 and #173? We have no GitHub Actions CI for this, and we need it, otherwise we can't verify this works. Further, we need this integrated with the `ipdk` CLI or it doesn't seem like it fits into the broader IPDK repository here.

This comment does not belong to this PR's conversation. Please add assignees to issues to foster issue awareness and visibility for stakeholders. I will reply in the conversations to the particular issues directly.

2022-07-01 10:26 UTC, intelfisz requested changes

2022-07-01 10:26 UTC, intelfisz commented on build/storage/tests/ut/README.md
>  The command below build all required dependencies and run the unit tests within
builds
runs

2022-07-01 10:26 UTC, intelfisz commented on build/storage/Dockerfile
> +# This image is placed on IPU and attaching to storage-target NVMe/TCP devices
missing '.' at the ends of sentences

2022-07-01 10:26 UTC, intelfisz commented on build/storage/tests/ut/README.md
> +Unit tests covers services written for IPDK.
covering

2022-07-01 10:51 UTC, artek-koltun commented on build/storage/tests/ut/README.md
>  The command below build all required dependencies and run the unit tests within
done

2022-07-01 10:51 UTC, artek-koltun commented on build/storage/Dockerfile
> +# This image is placed on IPU and attaching to storage-target NVMe/TCP devices
done

2022-07-01 10:51 UTC, artek-koltun commented on build/storage/tests/ut/README.md
> +Unit tests covers services written for IPDK.
done

2022-07-04 08:42 UTC, intelfisz approved these changes

2022-07-04 08:43 UTC, merged