shellcheck: Fix shellcheck
ipdk-io/ipdk pull request #199
Opened 2022-07-13 16:20 UTC by mestery

This allows shellcheck to fail correctly on errors, something it was not
doing previously.

Fixed in opi-poc here [1].

[1] https://github.com/opiproject/opi-poc/pull/114

Signed-off-by: Kyle Mestery <mestery@mestery.com>

2022-07-13 16:22 UTC, glimchb approved these changes
yes, please!

2022-07-13 18:33 UTC, mestery commented
@artek-koltun @intelfisz Can you both verify the changes to the storages scripts are ok? It turns out `shellcheck` has not been failing correctly, so a bunch of errors were introduced, which I cleaned up here as a part of making shellcheck enforce errors. Thanks!

2022-07-14 06:30 UTC, artek-koltun commented on build/storage/scripts/run_host_target_container.sh
> +#IMAGE_NAME="host-target"
Can we export this variable?

2022-07-14 06:31 UTC, artek-koltun requested changes

2022-07-14 06:31 UTC, artek-koltun commented on build/storage/scripts/run_ipu_storage_container.sh
> +#ALLOCATE_HUGEPAGES="true"
Can we export all these 3 variables?

2022-07-14 06:31 UTC, artek-koltun commented on build/storage/scripts/run_storage_target_container.sh
> +#ALLOCATE_HUGEPAGES="true"
Can we export all these 3 commented variables?

2022-07-14 14:04 UTC, merged